# @Author: Haupt Joshua <HauptJ>
# @Date:   26-Mar-2018
# @Email:  josh@hauptj.com
# @Filename: .travis.yml
# @Last modified by:   HauptJ
# @Last modified time: 02-Apr-2018

---
sudo: required

env:
  - distribution: centos
    version: 7

services:
  - docker

before_install:
  - 'sudo docker pull ${distribution}:${version}'
  - 'sudo docker build --no-cache --rm --file=travis/Dockerfile.${distribution}-${version} --tag=${distribution}-${version}:ansible travis'

script:
  # test database creation
  - container_id=$(mktemp)
  - 'sudo docker run --detach --privileged -v /sys/fs/cgroup:/sys/fs/cgroup:ro --volume="${PWD}":/etc/ansible/roles/test_role:ro ${distribution}-${version}:ansible > "${container_id}"'
  - 'sudo docker exec "$(cat ${container_id})" env ANSIBLE_FORCE_COLOR=1 ansible-playbook -v /etc/ansible/roles/test_role/travis/test.yml --syntax-check'
  - 'sudo docker exec "$(cat ${container_id})" env ANSIBLE_FORCE_COLOR=1 ansible-playbook -v /etc/ansible/roles/test_role/travis/test.yml'
  - 'sudo docker rm -f "$(cat ${container_id})"'
  # test database import
  - 'sed "s/mariadb_new_db: false/mariadb_new_db: true/g" defaults/main.yml'
  - 'cat defaults/main.yml'
  - container_id=$(mktemp)
  - 'sudo docker run --detach --privileged -v /sys/fs/cgroup:/sys/fs/cgroup:ro --volume="${PWD}":/etc/ansible/roles/test_role:ro ${distribution}-${version}:ansible > "${container_id}"'
  - 'sudo docker exec "$(cat ${container_id})" env ANSIBLE_FORCE_COLOR=1 ansible-playbook -v /etc/ansible/roles/test_role/travis/test.yml --syntax-check'
  - 'sudo docker exec "$(cat ${container_id})" env ANSIBLE_FORCE_COLOR=1 ansible-playbook -v /etc/ansible/roles/test_role/travis/test.yml'
  - 'sudo docker rm -f "$(cat ${container_id})"'

notifications:
    webhooks: https://galaxy.ansible.com/api/v1/notifications/
